# Generated by Django 2.0.1 on 2018-04-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=10, unique=True)),
                ('num_seats', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=30, unique=True)),
                ('country', models.CharField(max_length=30)),
                ('time_zone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_num', models.CharField(max_length=6, unique=True)),
                ('num_seats_booked', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='ON HOLD', max_length=9)),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(max_length=10)),
                ('dep_airport', models.CharField(max_length=30)),
                ('dest_airport', models.CharField(max_length=30)),
                ('dep_datetime', models.DateTimeField()),
                ('arr_datetime', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_reference_num', models.CharField(max_length=10, unique=True)),
                ('pay_reference_nu', models.CharField(max_length=10, unique=True)),
                ('booking_num', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid', models.BooleanField()),
                ('stamp', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('web_address', models.URLField()),
                ('account_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Flight'),
        ),
    ]
