# Generated by Django 2.0.1 on 2018-04-14 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_num', models.CharField(max_length=6, unique=True)),
                ('num_seats_booked', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='ON HOLD', max_length=9)),
                ('time', models.DurationField(default=datetime.timedelta(0, 1800))),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameModel(
            old_name='Payment_Providers',
            new_name='Payment_provider',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='flight',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='pay_reference_nu',
            new_name='pay_reference_num',
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Passenger'),
        ),
    ]
