# Generated by Django 2.0.1 on 2018-04-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180414_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='last_name',
            new_name='surname',
        ),
    ]
