# Generated by Django 2.0.1 on 2018-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20180415_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_provider',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
