# Generated by Django 2.0.1 on 2018-04-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_flight_flight_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_id',
        ),
    ]
